apiVersion: v1
kind: Service
metadata:
  name: customers
  labels:
    name: customers
    app: customers
spec:
  selector:
    name: customers 
  type: NodePort
  ports:
   - name: http
     port: 4646
     targetPort: 4646
     protocol: TCP
