apiVersion: v1
kind: Pod
metadata:
  name: customers
  labels:
    name: customers
    app: customers
spec: 
  containers: 
    - image: ramyacodes/customers
      name: customers
      ports: 
        - containerPort: 4646
